# Generated by Django 4.1.5 on 2023-02-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_rl", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
