# Generated by Django 4.1.5 on 2023-02-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_rl", "0003_delete_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
