# Generated by Django 4.1.5 on 2023-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdetails", "0005_rename_user_application_applicaant_payroll_payee"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                    ("Pending", "Pending"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
